package com.india;
public class MainFrame extends javax.swing.JFrame {
private String username, password;	
 public MainFrame(String u, String p)	
{
   this();	//Call to DC, Should be 1st statement
   username=u;
   password=p;
   this.setTitle("Dear "  + u + " Welcome in Medical App");
}

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMedicine = new javax.swing.JMenu();
        mnuMedicalFrame = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuMedicineSearch = new javax.swing.JMenuItem();
        mnuDistributor = new javax.swing.JMenu();
        mnuDistributorFrame = new javax.swing.JMenuItem();
        mnuManufacturer = new javax.swing.JMenu();
        mnuManufacturerFrame = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAboutUs = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuMedicine.setMnemonic('M');
        mnuMedicine.setText("Medicine");

        mnuMedicalFrame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuMedicalFrame.setMnemonic('M');
        mnuMedicalFrame.setText("Medicine Frame");
        mnuMedicalFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMedicalFrameActionPerformed(evt);
            }
        });
        mnuMedicine.add(mnuMedicalFrame);
        mnuMedicine.add(jSeparator1);

        mnuMedicineSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuMedicineSearch.setText("Search");
        mnuMedicineSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMedicineSearchActionPerformed(evt);
            }
        });
        mnuMedicine.add(mnuMedicineSearch);

        jMenuBar1.add(mnuMedicine);

        mnuDistributor.setMnemonic('D');
        mnuDistributor.setText("Distributor");

        mnuDistributorFrame.setText("Distributor Frame");
        mnuDistributor.add(mnuDistributorFrame);

        jMenuBar1.add(mnuDistributor);

        mnuManufacturer.setMnemonic('A');
        mnuManufacturer.setText("Manufacturer");

        mnuManufacturerFrame.setText("ManufacturerFrame");
        mnuManufacturerFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManufacturerFrameActionPerformed(evt);
            }
        });
        mnuManufacturer.add(mnuManufacturerFrame);

        jMenuBar1.add(mnuManufacturer);

        mnuHelp.setMnemonic('H');
        mnuHelp.setText("Help");

        mnuAboutUs.setText("About Us");
        mnuHelp.add(mnuAboutUs);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMedicalFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMedicalFrameActionPerformed
        // TODO add your handling code here:
        new MedicinesFrame(username,password).setVisible(true);
    }//GEN-LAST:event_mnuMedicalFrameActionPerformed

    private void mnuManufacturerFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManufacturerFrameActionPerformed
        // TODO add your handling code here:
        new ManufacturerFrame(username,password).setVisible(true);
    }//GEN-LAST:event_mnuManufacturerFrameActionPerformed

    private void mnuMedicineSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMedicineSearchActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMedicineSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame("ajay","vijay").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuAboutUs;
    private javax.swing.JMenu mnuDistributor;
    private javax.swing.JMenuItem mnuDistributorFrame;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuManufacturer;
    private javax.swing.JMenuItem mnuManufacturerFrame;
    private javax.swing.JMenuItem mnuMedicalFrame;
    private javax.swing.JMenu mnuMedicine;
    private javax.swing.JMenuItem mnuMedicineSearch;
    // End of variables declaration//GEN-END:variables
}
